database:
  ip: localhost
  port: 3306
  databasename: zander
  username: zander
  password: Passwordzander321
discord:
  token: ""
server:
  motdFirstLine: ""
  motdSecondLine: ""
  tablineHeader:
  tablineFooter:
annoucements:
  enabled: true
players:
