welcomemessage:
  - '&6&lServer Announcement:&r'
  - 'Hello there! You might be wondering why you are seeing this message. My name is &b&ezander&r and I have been developed by shadowolfyt. I will be running all of the operations here.'
  - ' '
  - 'All updates that the plugin receives will be addressed in Discord.'
  - 'If you would like to request something to be added or you would like to report a bug, please report it to shadowolfyt, or shadowolf#9212 on Discord.'
