name: zander
author: shadowolfyt
version: 1.0
main: com.shadowolf.zander.zander
description: A Minecraft Plugin written in Java

commands:
  heal:
    description: Heal yourself to full health.
  feed:
    description: Satisfy your hunger.