name: zander
author: shadowolfyt
version: 1.0
main: com.shadowolf.zander.zander
description: A Minecraft Plugin written in Java

commands:
  heal:
    description: Heal a user back to full health.
  feed:
    description: Satisfy a users hunger.
  starve:
    description: Deprive a user of their hunger.
  kick:
    description: Kicks a player from the server.