main: com.shadowolf.zander.zander
name: zander
version: 2.0
author: shadowolfyt
softdepend:
  - ActionBarAPI
  - TitleAPI

commands:
    heal:
      description: Heal a user back to full health.
      usage: /heal [target]
    feed:
      description: Satisfy a users hunger.
      usage: /feed [target]
    starve:
      description: Deprives users of their hunger.
      usage: /starve [target]
    gma:
      description: Changes players gamemode to adventure.
      usage: /gma [target]
      aliases: [adventure, a]
    gmc:
      description: Changes players gamemode to creative.
      usage: /gms [target]
      aliases: [creative, c]
    gms:
      description: Changes players gamemode to survival.
      usage: /gms [target]
      aliases: [survival, s]
    gmsp:
      description: Changes players gamemode to spectator.
      usage: /gmsp [target]
      aliases: [spectator, sp]
    fly:
      description: Allows players to fly.
      usage: /fly [target]
    profile:
      description: Display your profile stats.
      usage: /profile

permissions:
    zander.heal:
      default: op
    zander.feed:
      default: op
    zander.starve:
      default: op
    zander.survival:
      default: op
    zander.creative:
      default: op
    zander.adventure:
      default: op
    zander.spectator:
      default: op
    zander.fly:
      default: op
    zander.displayipaddress:
      default: op
